=head1 NAME

Config::Model::models::LCDd::curses - Configuration class LCDd::curses

=head1 VERSION

version 1.248

=head1 DESCRIPTION

Configuration classes used by L<Config::Model>

=head1 Elements

=head2 Foreground

color settings
foreground color [default: blue]I<< Optional. Type uniline. upstream_default: 'blue'.  >>

=head2 Background

background color when "backlight" is off [default: cyan]I<< Optional. Type uniline. upstream_default: 'cyan'.  >>

=head2 Backlight

background color when "backlight" is on [default: red]I<< Optional. Type uniline. upstream_default: 'red'.  >>

=head2 Size

display size [default: 20x4]I<< Optional. Type uniline. upstream_default: '20x4'.  >>

=head2 TopLeftX

What position (X,Y) to start the left top corner at...
Default: (7,7)I<< Optional. Type uniline. default: '7'.  >>

=head2 TopLeftY

I<< Optional. Type uniline. default: '7'.  >>

=head2 UseACS

use ASC symbols for icons & bars [default: no; legal, yes, no]I<< Optional. Type uniline. upstream_default: 'no'.  >>

=head2 DrawBorder

draw Border [default: yes; legal: yes, no]I<< Optional. Type enum. choice: 'yes', 'no'. upstream_default: 'yes'.  >>

=head1 SEE ALSO

=over

=item *

L<config-edit>

=back

=cut
