=head1 NAME

Config::Model::models::LCDd::imon - Configuration class LCDd::imon

=head1 VERSION

version 1.260

=head1 DESCRIPTION

Configuration classes used by L<Config::Model>

=head1 Elements

=head2 Device

select the device to use. I<< Optional. Type uniline. default: '/dev/lcd0'.  >>

=head2 Size

display dimensions. I<< Optional. Type uniline. default: '16x2'.  >>

=head1 SEE ALSO

=over

=item *

L<config-edit>

=back

=cut
