=head1 NAME

Config::Model::models::LCDd::imonlcd - Configuration class LCDd::imonlcd

=head1 VERSION

version 1.258

=head1 DESCRIPTION

Configuration classes used by L<Config::Model>

=head1 Elements

=head2 Protocol

Specify which iMon protocol should be used I<< Optional. Type uniline. upstream_default: '0'.  >>

=head2 OnExit

Set the exit behavior I<< Optional. Type uniline. upstream_default: '1'.  >>

=head2 Device

Select the output device to use I<< Optional. Type uniline. upstream_default: '/dev/lcd0'.  >>

=head2 Contrast

Select the displays contrast I<< Optional. Type integer. upstream_default: '200'.  >>

=head2 Size

Specify the size of the display in pixels I<< Optional. Type uniline. upstream_default: '96x16'.  >>

=head2 Backlight

Set the backlight state I<< Optional. Type enum. choice: 'on', 'off'. upstream_default: 'on'.  >>

=head2 DiscMode

Set the disc mode I<< Optional. Type uniline. upstream_default: '0'.  >>

=head1 SEE ALSO

=over

=item *

L<config-edit>

=back

=cut
