=head1 NAME

Config::Model::models::LCDd::imonlcd - Configuration class LCDd::imonlcd

=head1 VERSION

version 1.248

=head1 DESCRIPTION

Configuration classes used by L<Config::Model>

=head1 Elements

=head2 Protocol

Specify which iMon protocol should be used [legal: 0=15c2:ffdc device,
1=15c2:0038 device; default: 0]I<< Optional. Type uniline. default: '0'.  >>

=head2 OnExit

Set the exit behavior [legal: 0=leave shutdown message, 1=show the big clock,
2=blank device; default: 1]I<< Optional. Type uniline. default: '2'.  >>

=head2 Device

Select the output device to use [default: /dev/lcd0]I<< Optional. Type uniline. default: '/dev/lcd0'.  >>

=head2 Contrast

Select the displays contrast [default: 200; legal: 0-1000]I<< Optional. Type integer. upstream_default: '200'.  >>

=head2 Size

Specify the size of the display in pixels [default: 96x16]I<< Optional. Type uniline. upstream_default: '96x16'.  >>

=head2 Backlight

Set the backlight state [default: on; legal: on, off]I<< Optional. Type enum. choice: 'on', 'off'. upstream_default: 'on'.  >>

=head2 DiscMode

Set the disc mode [legal: 0=spin the "slim" disc - two disc segments,
1=their complement spinning; default: 0]I<< Optional. Type uniline. default: '0'.  >>

=head1 SEE ALSO

=over

=item *

L<config-edit>

=back

=cut
