=head1 NAME

Config::Model::models::LCDd::mx5000 - Configuration class LCDd::mx5000

=head1 VERSION

version 1.254

=head1 DESCRIPTION

Configuration classes used by L<Config::Model>

=head1 Elements

=head2 Device

Select the output device to use [default: /dev/hiddev0]I<< Optional. Type uniline. default: '/dev/hiddev0'.  >>

=head2 WaitAfterRefresh

Time to wait in ms after the refresh screen has been sent [default: 1000]I<< Optional. Type uniline. upstream_default: '1000'.  >>

=head1 SEE ALSO

=over

=item *

L<config-edit>

=back

=cut
