=head1 NAME

Config::Model::models::LCDd::pyramid - Configuration class LCDd::pyramid

=head1 VERSION

version 1.257

=head1 DESCRIPTION

Configuration classes used by L<Config::Model>

=head1 Elements

=head2 Device

device to connect to [default: /dev/lcd]I<< Optional. Type uniline. default: '/dev/ttyUSB0'.  >>

=head1 SEE ALSO

=over

=item *

L<config-edit>

=back

=cut
