=head1 NAME

Config::Model::models::LCDd::sed1520 - Configuration class LCDd::sed1520

=head1 VERSION

version 1.251

=head1 DESCRIPTION

Configuration classes used by L<Config::Model>

=head1 Elements

=head2 Port

Port where the LPT is. Usual values are 0x278, 0x378 and 0x3BC. I<< Optional. Type uniline. default: '0x378'.  >>

=head1 SEE ALSO

=over

=item *

L<config-edit>

=back

=cut
