=head1 NAME

Config::Model::models::LCDd::stv5730 - Configuration class LCDd::stv5730

=head1 VERSION

version 1.248

=head1 DESCRIPTION

Configuration classes used by L<Config::Model>

=head1 Elements

=head2 Port

Port the device is connected to [default: 0x378]I<< Optional. Type uniline. upstream_default: '0x378'.  >>

=head1 SEE ALSO

=over

=item *

L<config-edit>

=back

=cut
