---
abstract: 'Framework to create configuration validation tools and editors'
author:
  - 'Dominique Dumont'
  - 'Krzysztof Tyszecki'
build_requires:
  Module::Build: 0.34
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0.11
  Text::Template: 0
configure_requires:
  Module::Build: 0.34
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.102400'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Model
requires:
  Carp::Assert::More: 0
  Exception::Class: 0
  IO::File: 0
  Log::Log4perl: 1.11
  Moose: 0
  Parse::RecDescent: 1.90.0
  Scalar::Util: 0
  Term::ReadLine: 0
  YAML::Any: 0.303
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Config-Model
  homepage: http://config-model.wiki.sourceforge.net
  repository: http://config-model.hg.sourceforge.net:8000/hgroot/config-model/config-model
version: 1.208
