---
abstract: 'Edit and validate configuration data'
author:
  - 'Dominique Dumont (ddumont at cpan dot org)'
build_requires:
  Config::Tiny: 0
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0.11
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3601'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Model
provides:
  Config::Model:
    file: lib/Config/Model.pm
    version: 0.642
  Config::Model::AnyId:
    file: lib/Config/Model/AnyId.pm
    version: 1.0914
  Config::Model::AnyThing:
    file: lib/Config/Model/AnyThing.pm
    version: 1.0845
  Config::Model::AutoRead:
    file: lib/Config/Model/AutoRead.pm
    version: 1.1047
  Config::Model::CheckList:
    file: lib/Config/Model/CheckList.pm
    version: 1.0978
  Config::Model::Describe:
    file: lib/Config/Model/Describe.pm
    version: 1.0669
  Config::Model::DumpAsData:
    file: lib/Config/Model/DumpAsData.pm
    version: 1.0978
  Config::Model::Dumper:
    file: lib/Config/Model/Dumper.pm
    version: 1.1044
  Config::Model::Exception:
    file: lib/Config/Model/Exception.pm
    version: 1.0790
  Config::Model::Exception::Any:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::Load:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::LoadData:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::Model:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::ObsoleteElement:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::RestrictedElement:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::UnavailableElement:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::UnknownElement:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::UnknownId:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::WrongType:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::Xml:
    file: lib/Config/Model/Exception.pm
  Config::Model::HashId:
    file: lib/Config/Model/HashId.pm
    version: 1.1038
  Config::Model::IdElementReference:
    file: lib/Config/Model/IdElementReference.pm
    version: 1.0775
  Config::Model::Instance:
    file: lib/Config/Model/Instance.pm
    version: 1.1033
  Config::Model::ListId:
    file: lib/Config/Model/ListId.pm
    version: 1.0861
  Config::Model::Loader:
    file: lib/Config/Model/Loader.pm
    version: 1.0717
  Config::Model::Node:
    file: lib/Config/Model/Node.pm
    version: 1.1044
  Config::Model::ObjTreeScanner:
    file: lib/Config/Model/ObjTreeScanner.pm
    version: 1.0715
  Config::Model::Report:
    file: lib/Config/Model/Report.pm
    version: 1.0641
  Config::Model::Searcher:
    file: lib/Config/Model/Searcher.pm
    version: 1.1003
  Config::Model::SimpleUI:
    file: lib/Config/Model/SimpleUI.pm
    version: 1.0541
  Config::Model::TermUI:
    file: lib/Config/Model/TermUI.pm
    version: 1.0669
  Config::Model::Value:
    file: lib/Config/Model/Value.pm
    version: 1.1042
  Config::Model::ValueComputer:
    file: lib/Config/Model/ValueComputer.pm
    version: 1.0905
  Config::Model::WarpedNode:
    file: lib/Config/Model/WarpedNode.pm
    version: 1.1051
  Config::Model::WarpedThing:
    file: lib/Config/Model/WarpedThing.pm
    version: 1.1004
  Config::Model::WizardHelper:
    file: lib/Config/Model/WizardHelper.pm
    version: 1.1026
recommends:
  Config::Tiny: 0
requires:
  Carp::Assert::More: 0
  Exception::Class: 0
  IO::File: 0
  Log::Log4perl: 1.11
  Parse::RecDescent: v1.90.0
  Scalar::Util: 0
  Term::ReadLine: 0
resources:
  license: http://opensource.org/licenses/lgpl-license.php
version: 0.642
