# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-Model
version:      0.610
version_from: Model.pm
installdirs:  site
requires:
    Carp::Assert::More:            0
    Error:                         0
    Exception::Class:              0
    Log::Log4perl:                 0
    Parse::RecDescent:             1.90
    Scalar::Util:                  0
    Term::ReadLine:                0
    Term::ReadLine::Gnu:           0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
