---
abstract: 'Describe, edit and validate configuration data'
author:
  - 'Dominique Dumont (ddumont at cpan dot org)'
build_requires:
  Config::Tiny: 0
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0.11
  Text::Template: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Model
provides:
  Config::Model:
    file: lib/Config/Model.pm
    version: 1.001
  Config::Model::AnyId:
    file: lib/Config/Model/AnyId.pm
  Config::Model::AnyThing:
    file: lib/Config/Model/AnyThing.pm
  Config::Model::AutoRead:
    file: lib/Config/Model/AutoRead.pm
  Config::Model::Backend::Any:
    file: lib/Config/Model/Backend/Any.pm
  Config::Model::Backend::ShellVar:
    file: lib/Config/Model/Backend/ShellVar.pm
  Config::Model::Backend::Yaml:
    file: lib/Config/Model/Backend/Yaml.pm
  Config::Model::CheckList:
    file: lib/Config/Model/CheckList.pm
  Config::Model::Describe:
    file: lib/Config/Model/Describe.pm
  Config::Model::DumpAsData:
    file: lib/Config/Model/DumpAsData.pm
  Config::Model::Dumper:
    file: lib/Config/Model/Dumper.pm
  Config::Model::Exception:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::Any:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::Load:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::LoadData:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::Model:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::ObsoleteElement:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::RestrictedElement:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::UnavailableElement:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::UnknownElement:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::UnknownId:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::WrongType:
    file: lib/Config/Model/Exception.pm
  Config::Model::Exception::Xml:
    file: lib/Config/Model/Exception.pm
  Config::Model::HashId:
    file: lib/Config/Model/HashId.pm
  Config::Model::IdElementReference:
    file: lib/Config/Model/IdElementReference.pm
  Config::Model::Instance:
    file: lib/Config/Model/Instance.pm
  Config::Model::ListId:
    file: lib/Config/Model/ListId.pm
  Config::Model::Loader:
    file: lib/Config/Model/Loader.pm
  Config::Model::Node:
    file: lib/Config/Model/Node.pm
  Config::Model::ObjTreeScanner:
    file: lib/Config/Model/ObjTreeScanner.pm
  Config::Model::Report:
    file: lib/Config/Model/Report.pm
  Config::Model::Searcher:
    file: lib/Config/Model/Searcher.pm
  Config::Model::SimpleUI:
    file: lib/Config/Model/SimpleUI.pm
  Config::Model::TermUI:
    file: lib/Config/Model/TermUI.pm
  Config::Model::Value:
    file: lib/Config/Model/Value.pm
  Config::Model::ValueComputer:
    file: lib/Config/Model/ValueComputer.pm
  Config::Model::WarpedNode:
    file: lib/Config/Model/WarpedNode.pm
  Config::Model::WarpedThing:
    file: lib/Config/Model/WarpedThing.pm
  Config::Model::WizardHelper:
    file: lib/Config/Model/WizardHelper.pm
recommends:
  Config::Tiny: 0
requires:
  Carp::Assert::More: 0
  Exception::Class: 0
  IO::File: 0
  Log::Log4perl: 1.11
  Parse::RecDescent: v1.90.0
  Scalar::Util: 0
  Term::ReadLine: 0
  YAML::Any: 0.303
resources:
  license: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
version: 1.001
