---
abstract: 'Create tools to validate, migrate and edit configuration files'
author:
  - 'Dominique Dumont'
build_requires:
  Config::Model::Tester: '2.046'
  Module::Build: '0.34'
  Probe::Perl: '0'
  Term::ReadLine::Gnu: '0'
  Term::ReadLine::Perl: '0'
  Test::Command: '0.08'
  Test::Differences: '0'
  Test::Exception: '0'
  Test::File::Contents: '0'
  Test::Memory::Cycle: '0'
  Test::More: '0'
  Test::Warn: '0.11'
  YAML::Any: '0.303'
configure_requires:
  Module::Build: '0.34'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-Model
recommends:
  Fuse: '0'
  YAML::Any: '0.303'
requires:
  Carp: '0'
  Carp::Assert::More: '0'
  Data::Dumper: '0'
  English: '0'
  Exception::Class: '0'
  Fcntl: '0'
  File::Copy: '0'
  File::HomeDir: '0'
  File::Path: '0'
  Hash::Merge: '0.12'
  IO::File: '0'
  JSON: '0'
  List::MoreUtils: '0'
  Log::Log4perl: '1.11'
  Mouse: '0'
  Mouse::Util::TypeConstraints: '0'
  MouseX::NativeTraits: '0'
  MouseX::StrictConstructor: '0'
  POSIX: '0'
  Parse::RecDescent: v1.90.0
  Path::Tiny: '0'
  Pod::POM: '0'
  Scalar::Util: '0'
  Storable: '0'
  Term::ReadLine: '0'
  Text::Diff: '0'
  Text::Wrap: '0'
  perl: '5.010'
  warnings::register: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Config-Model
  homepage: https://github.com/dod38fr/config-model/wiki
  repository: git://github.com/dod38fr/config-model.git
version: '2.058'
