=head1 NAME

Config::Model::models::Debian::Dpkg - Configuration class Debian::Dpkg

=head1 VERSION

version 1.249

=head1 DESCRIPTION

Configuration classes used by L<Config::Model>

Model of Debian source package files (e.g debian/control, debian/copyright...)

=head1 Elements

=head2 meta

Specify meta parameters that will tune the behavior of this dpkg model. I<< Optional. Type node.  >>

=head2 control

Package control file. Specifies the most vital (and version-independent) information about the source package and about the binary packages it creates.I<< Optional. Type node.  >>

=head2 copyright - copyright and license information

copyright and license information of all files contained in this package. I<< Optional. Type node.  >>

=head2 source

I<< Optional. Type node.  >>

=head2 clean - list of files to clean

list of files to remove when dh_clean is run. Files names can include wild cards. For instance:

 build.log
 Makefile.in
 */Makefile.in
 */*/Makefile.in

I<< Optional. Type list of uniline.  >>

=head1 SEE ALSO

=over

=item *

L<config-edit>

=item *

L<Config::Model::models::Debian::Dpkg::Control>

=item *

L<Config::Model::models::Debian::Dpkg::Copyright>

=item *

L<Config::Model::models::Debian::Dpkg::Meta>

=item *

L<Config::Model::models::Debian::Dpkg::Source>

=back

=head1 AUTHOR

=over

=item Dominique Dumont


=back

=head1 COPYRIGHT

=over

=item 2010,2011 Dominique Dumont


=back

=head1 LICENSE

=over

=item LGPL2


=back

=cut
