=head1 NAME

Config::Model::models::Debian::Dpkg - Configuration class Debian::Dpkg

=head1 VERSION

version 1.240

=head1 DESCRIPTION

Configuration classes used by L<Config::Model>

Model of Debian source package files (e.g control, copyright...)

=head1 Elements

=head2 C<meta>

Specify meta parameters that will tune the behavior of this dpkg model. I<< Optional. Type node.  >>

=head2 C<control>

Package control file. Specifies the most vital (and version-independent) information about the source package and about the binary packages it creates. I<< Optional. Type node.  >>

=head2 C<copyright>

copyright and license information of all files contained in this package. I<< Optional. Type node.  >>

=head2 C<source>

I<< Optional. Type node.  >>

=head1 SEE ALSO

=over

=item *

L<config-edit>

=item *

L<Config::Model::models::Debian::Dpkg::Control>

=item *

L<Config::Model::models::Debian::Dpkg::Copyright>

=item *

L<Config::Model::models::Debian::Dpkg::Meta>

=item *

L<Config::Model::models::Debian::Dpkg::Source>

=back

=head1 AUTHOR

=over

=item Dominique Dumont


=back

=head1 COPYRIGHT

=over

=item 2010,2011 Dominique Dumont


=back

=head1 LICENSE

=over

=item LGPL2


=back

=cut